### ISSUE TITLE
is="body-bind" throws if on-* listeners are within dom-repeat/dom-if

### ISSUE THREAD

**Issue by ebidel** [PolymerLabs/polymer-experiments#5]
When an `on-*` listeners is defined in a conditional template or dom-repeat, the following error is thrown:

> Uncaught TypeError: Cannot read property '_createEventHandler' of undefined

Note: a listener on a node outside of one of these elements works fine. It's something to do with the late binding.

```
<body is="body-bind">
 <span on-tap="sayHi">listener outside does not throw</span>

<template is="dom-if" ...>
  <span on-tap="sayHi">throws error</span>
 </template>

<template is="dom-repeat" items="[[versions]]">
  <div on-tap="sayHi">throws error</div>
</template>
</body>
```

<img width="1145" alt="screen shot 2015-12-07 at 9 56 21 am" src="https://cloud.githubusercontent.com/assets/238208/11635132/9a0ccadc-9cc9-11e5-9fdf-363f432b8195.png">

**Comment by GeoloeG-IsT** [comment]
juicy one! :)

**Comment by ebidel** [comment]
Also seeing issues with computed functions claiming to be `undefined` if they're within these template elements.
